### ISSUE TITLE
Allow people to paste in JSON Schemas that will be used for the remainder of the lifecycle of the app.

### ISSUE THREAD

**Issue by robertmassaioli** [atlassian-labs/json-schema-viewer#17]
This was a request here: https://json-schema.slack.com/archives/C5CF75URH/p1612213784250100?thread_ts=1612208453.249400&cid=C5CF75URH

I suspect that the issue is that people want to be able to live edit their JSON Schema. The more I think about it, the more that I think that it would be better to have them upload the file somewhere that this tool can point to and just document that.

**Comment by robertmassaioli** [comment]
For now, I'm going to treat this as "Issue solved" since I think that it meets the use-case without requiring more effort.

**Comment by mohag** [comment]
I'm trying to view a Schema that AWS gives for an EKS addon, so an option to paste the schema in would be useful... (Otherwise I need to upload someone else's schema to GIST or similar...
